# Generated by Django 2.2.2 on 2019-06-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('Nco_Cob', models.AutoField(primary_key=True, serialize=False, verbose_name='No. Recibo')),
                ('Fco_Cob', models.DateField(verbose_name='Fecha Recibo')),
                ('Mco_Cob', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto del Recibo')),
                ('Con_Cob', models.CharField(blank=True, max_length=50, null=True, verbose_name='Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Psicologia',
            fields=[
                ('Nre_Psi', models.AutoField(primary_key=True, serialize=False, verbose_name='No. Recibo')),
                ('Tre_Psi', models.CharField(choices=[('AU', 'Autorizacion'), ('EX', 'Excusa'), ('RE', 'Reporte'), ('RT', 'Retiro')], max_length=2, verbose_name='Tipos De Reporte')),
                ('Fre_Psi', models.DateField(verbose_name='Fecha Reporte')),
                ('Mre_Psi', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('Rec_Psi', models.TextField(blank=True, null=True, verbose_name='Recomendación')),
                ('Alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Alumno')),
                ('Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Empleado', verbose_name='Profesor/Empleado')),
                ('Grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lec_Not', models.CharField(blank=True, max_length=9, null=True, verbose_name='Año Léctivo')),
                ('Nt1_Not', models.IntegerField(blank=True, null=True, verbose_name='Ago-Oct')),
                ('Nt2_Not', models.IntegerField(blank=True, null=True, verbose_name='Nov-Ene')),
                ('Nt3_Not', models.IntegerField(blank=True, null=True, verbose_name='Feb-Mar')),
                ('Nt4_Not', models.IntegerField(blank=True, null=True, verbose_name='Abr-Jun')),
                ('Pfi_Not', models.IntegerField(blank=True, null=True, verbose_name='P. Final')),
                ('Pco_Not', models.IntegerField(blank=True, null=True, verbose_name='Completivo')),
                ('Pex_Not', models.IntegerField(blank=True, null=True, verbose_name='Extraordinario')),
                ('Alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Alumno')),
                ('Asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Asignatura')),
                ('Grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Grado')),
            ],
        ),
    ]
