# Generated by Django 2.2.2 on 2019-06-20 00:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('Id_Asi', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Identificación')),
                ('Nom_Asi', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Cho_Asi', models.IntegerField(verbose_name='Cantidad de Horas')),
                ('Dpt_Asi', models.CharField(choices=[('IDI', 'Idiomas'), ('MAT', 'Matemáticas'), ('SOC', 'Sociales'), ('NAT', 'Naturales'), ('TUR', 'Turismo'), ('HUM', 'Humanidades'), ('GES', 'Gestión'), ('INF', 'Informática'), ('ENF', 'Enfermería'), ('CON', 'Contabilidad'), ('MER', 'Mercadeo'), ('ESP', 'Español')], max_length=3, verbose_name='Departamento')),
                ('Tip_Asi', models.CharField(choices=[('A', 'Académica'), ('T', 'Técnica')], max_length=1, verbose_name='Tipo Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Id_Emp', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificación')),
                ('Nom_Emp', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Dir_Emp', models.CharField(max_length=40, verbose_name='Dirección')),
                ('Nac_Emp', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nacionalidad')),
                ('Sex_Emp', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('Dpt_Emp', models.CharField(choices=[('IDI', 'Idiomas'), ('MAT', 'Matemáticas'), ('SOC', 'Sociales'), ('NAT', 'Naturales'), ('TUR', 'Turismo'), ('HUM', 'Humanidades'), ('GES', 'Gestión Adm.'), ('INF', 'Informatíca'), ('ENF', 'Enfermería'), ('CON', 'Contabilidad'), ('MER', 'Mercadeo'), ('AMD', 'Administrativo')], max_length=3, verbose_name='Departamento')),
                ('Cor_Emp', models.EmailField(blank=True, max_length=35, null=True, verbose_name='Correo Electrónico')),
                ('Fna_Emp', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Tfi_Emp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo')),
                ('Tmo_Emp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil')),
                ('Tip_Emp', models.CharField(choices=[('P', 'Profesor'), ('M', 'Maestría'), ('D', 'Doctorado'), ('E', 'Empleado')], max_length=1, verbose_name='Titulación')),
                ('Tsa_Emp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Sangre')),
                ('Car_Emp', models.CharField(choices=[('A', 'Diector'), ('B', 'Sub-Director Académico'), ('C', 'Sub-Director Adm.'), ('D', 'Maestro'), ('E', 'Psicologo'), ('F', 'Vinculacion Externa'), ('G', 'Coordinacion Academica.'), ('H', 'Coordinacion Tecnica'), ('I', 'Contador'), ('J', 'Apoyo'), ('K', 'Conserje'), ('L', 'Chofer')], max_length=1, verbose_name='Cargo')),
                ('Fot_Emp', models.ImageField(upload_to='D:\\Colegio\\FotEmp\\FRANCIA.JPG')),
            ],
        ),
        migrations.CreateModel(
            name='Tutore',
            fields=[
                ('Id_Tut', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificación')),
                ('Nom_Tut', models.CharField(max_length=30, verbose_name='Nombre')),
                ('Dir_Tut', models.CharField(max_length=40, verbose_name='Dirección')),
                ('Nac_Tut', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nacionalidad')),
                ('Sex_Tut', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('Fna_Tut', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Ced_Tut', models.CharField(blank=True, max_length=13, null=True, verbose_name='Cédula')),
                ('Tfi_Tut', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo')),
                ('Tmo_Tut', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('Id_Gra', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Id-Grado')),
                ('Asi01', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi02', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi03', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi04', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi05', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi06', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi07', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi08', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi09', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi10', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi11', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi12', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi13', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi14', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi15', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Asi16', models.CharField(blank=True, max_length=11, null=True, verbose_name='Asignatura')),
                ('Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Empleado', verbose_name='Prof. Titular')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Id_Alu', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificación')),
                ('Ape_Alu', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('Nom_Alu', models.CharField(max_length=20, verbose_name='Nombres')),
                ('Dir_Alu', models.CharField(max_length=40, verbose_name='Dirección')),
                ('Nac_Alu', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nacionalidad')),
                ('Cpr_Alu', models.CharField(max_length=40, verbose_name='Centro Procedencia')),
                ('Con_Alu', models.CharField(choices=[('A', 'Activo'), ('S', 'Separado')], max_length=1, verbose_name='Condición')),
                ('Sex_Alu', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('Fna_Alu', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Cor_Alu', models.EmailField(blank=True, max_length=35, null=True, verbose_name='Correo Electrónico')),
                ('Tfi_Alu', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo')),
                ('Tmo_Alu', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil')),
                ('Tsa_Alu', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Sangre')),
                ('Mod_Alu', models.CharField(choices=[('G', 'General'), ('T', 'Técnico')], max_length=1, verbose_name='Modalidad')),
                ('Are_Alu', models.CharField(choices=[('GAT', 'Gestión Adminidtrativa y Tributaría'), ('ENF', 'Enfermería'), ('INF', 'Informáica'), ('MER', 'Mercadeo'), ('TUR', 'Turismo')], max_length=3, verbose_name='Area')),
                ('Doc_Alu', multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Acta De Nacimiento'), ('CM', 'Certificado Médico'), ('F2', 'Fotos 2x2'), ('CG', 'Certificado de Grado')], max_length=11, verbose_name='Documentos')),
                ('Fot_Alu', models.CharField(blank=True, max_length=6, null=True)),
                ('Tutore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Tutore', verbose_name='Tutor')),
            ],
        ),
    ]
