# Generated by Django 2.2.4 on 2019-08-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='website',
            new_name='Sitio_Web',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='Telefono',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='Usuario',
        ),
    ]
